### ISSUE TITLE
switchboard数据集

### ISSUE THREAD

**Issue by kovnew** [scir-zywang/self-training-self-supervised-disfluency#2]
请问能留一个SWBD数据集下载链接吗？

**Comment by scir-zywang** [comment]
你好，由于版权问题，我无权分发SWBD数据集，需要自行购买。

**Comment by Kiteflyingee** [comment]
> 你好，由于版权问题，我无权分发SWBD数据集，需要自行购买。

刚开始做这个，在网上只找到SWDA数据集，请问这两个是不是就是一个数据集呀，感谢🙏
![image](https://user-images.githubusercontent.com/12490322/148643114-96ed4932-71b5-4584-b1e6-2b78d90bb3b7.png)

**Comment by HankLiu10** [comment]
> > 你好，由于版权问题，我无权分发SWBD数据集，需要自行购买。
> 
> 刚开始做这个，在网上只找到SWDA数据集，请问这两个是不是就是一个数据集呀，感谢🙏 ![image](https://user-images.githubusercontent.com/12490322/148643114-96ed4932-71b5-4584-b1e6-2b78d90bb3b7.png)

您好，请问解决了吗，我也遇到了不知道用哪个数据集的问题
